baseURL = 'https://perttunurmi.github.io/personal-website/'
languageCode = 'en-us'
title = 'Perttu Nurmi'
theme = "hyde"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/perttunurmi/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/perttunurmi/"}
  ]

[params]
  description = "Just another poorly thought-out tech blog"
